name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - working-directory: './plain'
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn build
    - run: yarn test
