name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: yarn install
      working-directory: './plain'

    - name: Build
      run: yarn build
      working-directory: './plain'

    - name: Test
      run: yarn test
      working-directory: './plain'
