name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - working-directory: './plain'
    - name: Install dependencies
    - run: yarn install
    - name: Build
    - run: yarn build
    - name: Test
    - run: yarn test
